spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  error:
    include-message: always